parameters:
  llm_main: gpt-4-0125-preview
  llm_helper: gpt-3.5-turbo
  embedding_model: text-embedding-3-small
  database_path: chromadb
  allowed_file_types: [txt, md]
  search_type: mmr
  docs_to_use: 2
  docs_to_process: 50
  min_prompt_count: 0
  max_prompt_count: 3

welcome_message: |
  This innovative web app uses artificial intelligence to facilitate discussions on philosophy.

  ### How to Use Eidos

  1. Select a topic
  2. Customize experience
  3. Engage in dialogue
  4. Download the conversation
  5. Answer three multiple-choice questions
  6. Fill-up the user survey form

templates:
  greeting: What's something you believe to be true?

  main_instruction: |
    Assume the role of a philosophy professor talking. Engage the user in dialogue based on the Socratic method. The goal is to guide the user to think critically about their belief. If the dialogue strays from philosophy, guide it back to the original topic.

    Your responses should follow three steps:

    1. Analyze the user's claim.
    2. Present counterarguments or alternative viewpoints.
    3. End with a question to encourage further reflection.

    Your response must follow the following criteria:

    {additional_instructions}

    Use the following documents to answer the query. Ignore any irrelevant document or section to focus on the user's query.

    {{context}}

  query_expansion: |
    Your task is to rewrite the last user's message to add context and depth, considering our conversation so far. Do not answer the message directly. Instead, expand it only. The expansion should provide specific details that were not initially mentioned but are relevant to the original message. Your response should include 10 specific and accurate keywords that capture the essence of the expanded content.

    Format your response as follows:

    ```
    <EXPANDED_MESSAGE>

    <KEYWORD_1>, <KEYWORD_2>, ..., <KEYWORD_10>
    ```

  answer: |
    Within the context of our dialogue, your task is to check for any inconsistencies in the user's statement. In particular, identify any logical fallacies, unsupported claims, or contradictions to previous statements.

    If any inconsistencies are present, provide a background explanation to point out the inconsistency and ask the user for clarification.

    If the statement is consistent, explore the deeper implication of the statement and ask a follow-up question to deepen the conversation.

    Here's the statement you need to analyze:

    ```
    {question}
    ```

tips:
  first_message: |
    Share an opinion. We'll explore it together for the entire conversation.

topics:
  - branch: ethics
    title: Moral Problems
    caption: Navigate moral dilemmas and understand ethical behaviors' impacts.
    instruction: |
      The dialogue shall strictly focus on ethics or related fields of philosophy. In particular, explore ethical theories, moral dilemmas, and the consequences of ethical decisions. The goal is to enhance understanding of ethical principles and their application in real-world scenarios.

  - branch: logic
    title: Reasoning and Argumentation
    caption: Learn to reason and construct arguments with logical precision.
    instruction: |
      The dialogue shall strictly focus on logic or related fields of philosophy. In particular, analyze logical fallacies, argument structures, and principles of deductive and inductive reasoning. The goal is to improve critical thinking skills and the ability to construct coherent arguments.

  - branch: metaphysics
    title: Nature of Reality
    caption: Examine the essence of reality, being, and the universe's nature.
    instruction: |
      The dialogue shall strictly focus on metaphysics or related fields of philosophy. In particular, delve into the concepts of existence, causality, space and time, and the possibility of free will. The goal is to deepen the understanding of the fundamental nature of reality and existence.

  - branch: epistemology
    title: Knowledge and Belief
    caption: Investigate how we acquire knowledge and its boundaries.
    instruction: |
      The dialogue shall strictly focus on epistemology or related fields of philosophy. In particular, discuss the sources and limits of knowledge, the nature of belief and justification, and the challenge of skepticism. The goal is to explore the basis of knowledge and its implications for understanding the world.

  - branch: aesthetics
    title: Art, Beauty, and Taste
    caption: Explore the philosophy of beauty and art's profound impact.
    instruction: |
      The dialogue shall strictly focus on aesthetics or related fields of philosophy. In particular, examine the nature of beauty, the interpretation of art, and the aesthetic experience. The goal is to appreciate the philosophical dimensions of art and beauty and their significance in human experience.

  - branch: politics
    title: Political Philosophy
    caption: Debate governance, rights, and societal duties philosophically.
    instruction: |
      The dialogue shall strictly focus on political philosophy or related fields of philosophy. In particular, debate theories of justice, governance, rights, and responsibilities within societies. The goal is to critically engage with political ideas and understand their impact on contemporary societal structures.

language_styles:
  - title: casual
    caption: Discuss philosophy in everyday language, making it accessible.
    instruction: |
      Employ relatable, everyday language to demystify philosophical concepts for a broader audience. Simplify intricate ideas to their core components, ensuring accessibility while preserving the integrity of philosophical thought.

  - title: formal
    caption: Engage in precise, academic-level philosophical discussions.
    instruction: |
      Utilize a formal tone, employing precise academic terminology and well-structured arguments. Strive for clear, in-depth explanations and analyses, ensuring that discussions adhere to scholarly standards of argumentation and evidence.

# TODO: Update prompts for consistent response lengths: quick-paced (4 sentences), in-depth (6 sentences)
dialogue_paces:
  - title: fast-paced
    caption: Swiftly explore philosophical ideas with quick insights.
    instruction: |
      Maintain brevity in responses, aiming for quick, sharp insights into philosophical ideas. Prioritize speed and clarity to foster a rapid, interactive dialogue. Always limit your response to two short sentences.

  - title: in-depth
    caption: Deep dive into philosophy with thorough analyses and reflections.
    instruction: |
      Provide comprehensive, detailed responses that delve deeply into philosophical concepts, ensuring thorough analysis and reflection. Emphasize length, allowing for extensive exploration and understanding of each topic. Always your response to one paragraph.

# TODO: Improve the survey questions for better feedback
survey:
  open-ended:
    - Describe your experience with the Socratic dialogue. Highlight any specific interactions.

  likert-scale:
    - I found the dialogues engaging and interesting.
    - Eidos clarified complex concepts well.
    - I would recommend Eidos to others.
