parameters:
  llm_main: gpt-4
  llm_helper: gpt-3.5-turbo

  embedding_model: text-embedding-3-small
  embedding_dimensions: 512
  embedding_chunk_size: 1000
  embedding_chunk_overlap: 200

  allowed_file_types: [txt, md]
  search_type: mmr
  docs_to_use: 2
  docs_to_process: 50

  min_prompt_count: 2
  max_prompt_count: 5

welcome_message: |
  #### How does it work?

  Eidos helps you share your beliefs, spot contradictions, and consider other views by using the Socratic Method. This method involves asking questions and having discussions.

templates:
  greeting: |
    What's something you believe to be true about {topic}?

  system: |
    Assume the role of a philosopher. We are exchanging SMS messages using the Socratic method. Help me understand my beliefs, address their inconsistencies, and consider other perspectives. If I stray from philosophy, gently guide me back to the original topic.

    {additional_instructions}

    {{context}}

  rag_route: |
    Given a message, determine whether reading philosophical texts is necessary to generate a response. A message requires philosophical texts if it mentions a concept, argument, or philosopher that you think requires further explanation.

    If it requires texts, reply `fetch documents`. If not, reply `continue conversation`. Respond with these exact phrases. Do not include the backticks.

    Here's the message you need to consider:

    ```
    {user_message}
    ```

  context: |
    Before replying, read and understand the texts below. Use them in the conversation if they relate to my last message. If not, use your own knowledge to lead the conversation.

    {context}

  query_expansion: |
    Rewrite my last message to add context and depth relevant to our conversation. Do not answer the last message directly. Instead, expand it only. The revision should have more details that were not initially mentioned. Finally, conclude with 20 specific keywords or jargons related to the expanded content.

    Format your response as follows:

    ```
    <EXPANDED_MESSAGE>

    <KEYWORD_1>, <KEYWORD_2>, ..., <KEYWORD_20>
    ```

  answer: |
    Analyze the given reply to identify any inconsistencies. These include logical fallacies, unsupported claims, and internal contradictions. If you find any, explain the inconsistency and ask me for clarification. If the reply is consistent, share your thoughts and ask me a follow-up question. For each case, your analysis should be followed by a single question only.

    {additional_instructions}

    Here's the reply you need to consider:

    ```
    {{user_message}}
    ```

  summary: |
    Summarize our entire conversation so far. Highlight the key points. Use direct anc concise language. Shorten your sentences.

    Format your response as follows:

    ```
    In our conversation, we learned these ideas:

    - <KEY_POINT_1>
    - <KEY_POINT_2>
    - <KEY_POINT_3>
    ```

    Do not include the backticks.

tips:
  first_message: |
    Share an opinion. We'll explore it together for the entire conversation.

topics:
  - branch: ethics
    title: moral problems
    caption: Understand impact of ethical behaviors.
    instruction: |
      Focus only on ethics. Help me enhance my understanding of moral principles and their practical application.

  - branch: aesthetics
    title: art and beauty
    caption: Explore the profound impact of aesthetics.
    instruction: |
      Focus only on aesthetics. Help me understand the concepts of art, beauty, and taste.

  - branch: logic
    title: reasoning
    caption: Learn to argue with logical precision.
    instruction: |
      Focus only on logic. Help me improve my critical thinking skills and the ability to construct clear and coherent arguments.

  - branch: epistemology
    title: knowledge
    caption: Investigate how we acquire knowledge.
    instruction: |
      Focus only on epistemology. Help me explore the basis of knowledge and its implications for understanding the world.

language_styles:
  - title: quick and casual
    caption: Discuss in everyday language.
    instruction: |
      I can only understand basic English. My vocabulary is also limited. Therefore, use very simple sentences. Avoid explanations. Use everyday language like you would in a real SMS message. Limit your response to 3 short sentences.

  - title: in-depth and formal
    caption: Engage in academic-level discussions.
    instruction: |
      I understands jargons and complex concepts. So, feel free to use technical terms. However, I prefer readable and short response. Limit your response to 4 short sentences.

survey:
  open-ended:
    - Describe your experience. Highlight any specific interactions.

  likert-scale:
    - Effective in helping me examine my beliefs more critically
    - Made me more open to considering alternative perspectives
    - Clearly identified inconsistencies in my beliefs

  multiple-choice:
    - question: |
        Which aspect is most valuable in examining your beliefs?
      options:
        - Engaging in dialogue
        - Identifying inconsistencies in my belief
        - Being introduced to alternative perspectives
        - Reference to philosophical texts

    - question: |
        How did Eidos change your approach to examining your beliefs?
      options:
        - I am more careful of my beliefs and assumptions.
        - I actively seek out alternative viewpoints more often.
        - I reflect more on the foundations of my beliefs.
        - There has been no significant change in my approach.

    - question: |
        Which feature needs the most improvement?
      options:
        - AI's understanding of complex beliefs
        - Diversity and selection of philosophical texts
        - Ability to handle sensitive topics more delicately
        - Personalization of dialogue based on user responses
